### ISSUE TITLE
Become user root (as in ansible)

### ISSUE THREAD

**Issue by pogoba** [numtide/deploykit#10]
**Is your feature request related to a problem? Please describe.**

On ssh servers without `AllowRootLogin yes` i can not directly log in with root. Instead i log in via a normal user and then elevate my privileges via `sudo`. 

**Describe the solution you'd like**

In ansible you can use the `Become: yes` and `BecomeUser: root` directive to instruct ansible to wrap your remote command with sudo and do the password input for you. ([become/sudo.py](https://github.com/ansible/ansible/blob/e10851d495fd073e22bdd78ec45a1f8019604b35/lib/ansible/plugins/become/sudo.py))

I want the same in deploykit. 

**Describe alternatives you've considered**

In some scenarios, allowing ssh root login can be considered insecure. 

**Additional context**

One solution is to expect sudo to exist and just send the password to its stdin (see [this commit](https://gitlab.pogobanane.de/server/nixos-server/-/commit/734196d4e4cdb9b51e5a1c3b1da46a303ad9c8dc))

I believe this can likely be added without introducing breaking changes.

**Comment by Mic92** [comment]
There is a become root option: https://github.com/numtide/deploykit/blob/050ad9db8085543ee0f9cae8a0efb7a62612e068/deploykit/__init__.py#L405
